HW06/tasktracker/lib/tasktracker_web/router.ex
defmodule TasktrackerWeb.Router do
  use TasktrackerWeb, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :get_current_user
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

#Attribution: https://github.com/NatTuck/microblog/blob/part-two/lib/microblog_web/router.ex

  def get_current_user(conn, _params) do
    # TODO: Move this function out of the router module.
    user_id = get_session(conn, :user_id)
    if user_id do
      user = Tasktracker.Accounts.get_user(user_id || -1)
      assign(conn, :current_user, user)
    else
      assign(conn, :current_user, nil)
    end


  end

  scope "/", TasktrackerWeb do
    pipe_through :browser # Use the default browser stack

    get "/", PageController, :index
    get "/usertasks", PageController, :usertasks

    resources "/users", UserController
    resources "/tasks", TaskController


    post "/session", SessionController, :create
    delete "/session", SessionController, :delete

  end

  # Other scopes may use custom stacks.
  # scope "/api", TasktrackerWeb do
  #   pipe_through :api
  # end
end

HW06/tasktracker/lib/tasktracker_web/templates/page/index.html.eex
    <h1>Log In</h1>
    <!-- session_path(@conn, :create) -->
    <%= form_tag("/session", method: :post) do %>
      <div class="form-group">
        Email
        <input type="email" name="email" placeholder="user@example.com" >
      </div>
      <!-- passwords come later -->
      <div class="form-group">
        <button class="btn btn-primary">Log in</button>
        <%= link "Register", to: user_path(@conn, :new) %>
      </div>
    <% end %>

HW06/tasktracker/lib/tasktracker_web/templates/page/usertasks.html.eex
<h2> ALL TASKS </h2>
<%= link "Create Task", to: "/tasks/new", class: "btn btn-default btn-xs"%>

<%= Enum.map @tasks, fn task -> %>
<%= if task.user == @current_user do %>
<div class="row">
  <div class="col">
    <div class="card">
      <div class="card-body">
        <h2 class="card-title">Assigned to User:<%= task.user.name %></h2>
	      <p>Task Name: <%= task.task_name %></p>
       	 <p>Task Description: <%= task.task_description %></p>
	       <p>Status of task (True if task is completed)  :  <%= task.iscomplete %></p>
	      <p>Time spent on tasks: <%= task.timespent %></p>
        <span><%= link "Edit task", to: task_path(@conn, :edit, task), class: "btn btn-default btn-xs" %></span>
        <span><%= link "Delete task", to: task_path(@conn, :delete, task), method: :delete, data: [confirm: "Are you sure?"], class: "btn btn-danger btn-xs" %></span>

      </div>
    </div>
  </div>
</div>
<% end %>
<% end %>